export interface GolfCourse {
  id: string;
  name: string;
  region: string;
  province: string;
  lat: number;
  lng: number;
  holes: number;
  established: number;
  description: string;
  hints: string[];
  features: string[];
  recommendedClubs: string[];
  difficulty: "쉬움" | "중간" | "어려움";
  difficultyTips: string[];
}

export const golfCourses: GolfCourse[] = [
  // 서울/경기
  {
    id: "sg001",
    name: "서울컨트리클럽",
    region: "서울/경기",
    province: "서울",
    lat: 37.4419,
    lng: 127.0891,
    holes: 18,
    established: 1970,
    description: "한국 최초의 현대식 골프장. 강남의 명문 클럽으로 많은 유명인사들이 즐겨 찾음.",
    hints: ["강남 명문클럽", "한국 최초 현대식", "국내 가장 오래됨"],
    features: ["명문 클럽", "역사적 가치", "프로 캐디", "회원제"],
    recommendedClubs: ["드라이버", "3목", "9아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 중요한 명문 코스입니다", "페어웨이 유지가 엄격하니 주의하세요", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg002",
    name: "남서울컨트리클럽",
    region: "서울/경기",
    province: "서울",
    lat: 37.4244,
    lng: 127.0779,
    holes: 18,
    established: 1972,
    description: "서울 남부지역의 대표 골프장. 접근성이 좋고 고급스러운 시설로 인기.",
    hints: ["서울 남부", "접근성 좋음", "고급스러운 시설"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg003",
    name: "강남컨트리클럽",
    region: "서울/경기",
    province: "서울",
    lat: 37.4847,
    lng: 127.0647,
    holes: 18,
    established: 1988,
    description: "강남 중심부의 프리미엄 골프장. 유명 기업인과 정계인사들의 멤버십 선호지.",
    hints: ["강남 프리미엄", "기업인 선호", "역사 깊음"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg004",
    name: "서울올림픽CC",
    region: "서울/경기",
    province: "서울",
    lat: 37.5169,
    lng: 127.1084,
    holes: 18,
    established: 1986,
    description: "1988 서울올림픽을 기념해 조성된 골프장. 올림픽공원 인근 위치.",
    hints: ["1988 올림픽 기념", "올림픽공원", "역사적 의미"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg005",
    name: "경기컨트리클럽",
    region: "서울/경기",
    province: "경기",
    lat: 37.2789,
    lng: 127.0128,
    holes: 18,
    established: 1973,
    description: "경기도 남부의 정통 명문 클럽. 아름다운 자연환경과 뛰어난 코스 난이도로 유명.",
    hints: ["경기 명문", "난이도 높음", "자연환경 좋음"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg006",
    name: "여주컨트리클럽",
    region: "서울/경기",
    province: "경기",
    lat: 37.3118,
    lng: 127.6393,
    holes: 18,
    established: 1990,
    description: "남한강변의 풍경이 아름다운 골프장. 경치 좋은 홀로 유명.",
    hints: ["여주 남한강변", "경치 아름다움", "강변 코스"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg007",
    name: "이천컨트리클럽",
    region: "서울/경기",
    province: "경기",
    lat: 37.2648,
    lng: 127.4419,
    holes: 18,
    established: 1989,
    description: "이천의 명품 골프장. 도자기로 유명한 지역에 위치.",
    hints: ["이천 도자기", "명품 코스", "경기동부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg008",
    name: "양주CC",
    region: "서울/경기",
    province: "경기",
    lat: 37.8246,
    lng: 127.0656,
    holes: 18,
    established: 1987,
    description: "수도권 북부의 대표 골프장. 잠실, 일산 등 주요 지역과 가까움.",
    hints: ["경기 북부", "수도권 접근", "잠실·일산 인근"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "sg009",
    name: "남이섬CC",
    region: "서울/경기",
    province: "경기",
    lat: 37.5096,
    lng: 127.0956,
    holes: 18,
    established: 1995,
    description: "남이섬의 자연을 활용한 특색 있는 골프장. 관광지로도 유명.",
    hints: ["남이섬 인근", "자연경관", "관광 콘텐츠"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  // 강원
  {
    id: "kw001",
    name: "강원컨트리클럽",
    region: "강원",
    province: "강원",
    lat: 37.2565,
    lng: 127.1062,
    holes: 18,
    established: 1983,
    description: "강원도 중부의 대표 골프장. 산악 지형을 활용한 독특한 코스 설계.",
    hints: ["강원 중부", "산악 코스", "독특한 설계"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "kw002",
    name: "용평CC",
    region: "강원",
    province: "강원",
    lat: 37.6426,
    lng: 127.7191,
    holes: 18,
    established: 1991,
    description: "용평리조트 내 위치한 골프장. 스키장으로도 유명한 복합 레저시설.",
    hints: ["용평리조트", "스키장 인근", "복합 레저"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "kw003",
    name: "춘천CC",
    region: "강원",
    province: "강원",
    lat: 37.8928,
    lng: 127.7353,
    holes: 18,
    established: 1992,
    description: "춘천호 근처의 아름다운 경치를 자랑하는 골프장. 영화 촬영지로도 유명.",
    hints: ["춘천호 근처", "영화 촬영지", "호수 경관"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "kw004",
    name: "원주CC",
    region: "강원",
    province: "강원",
    lat: 37.3405,
    lng: 127.9578,
    holes: 18,
    established: 1989,
    description: "원주의 중심 골프장. 접근성 좋고 잘 관리된 시설로 유명.",
    hints: ["원주 중심", "접근성 좋음", "시설 우수"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "kw005",
    name: "강릉CC",
    region: "강원",
    province: "강원",
    lat: 37.7518,
    lng: 128.8993,
    holes: 18,
    established: 1994,
    description: "동해 해안 근처의 골프장. 동계올림픽 개최지로 유명한 강릉 위치.",
    hints: ["강릉 위치", "동해 근처", "올림픽 개최지"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  // 충청
  {
    id: "cc001",
    name: "청주CC",
    region: "충청",
    province: "충북",
    lat: 36.6424,
    lng: 127.4890,
    holes: 18,
    established: 1988,
    description: "청주의 대표 골프장. 충북 지역 경제인들의 사랑을 받는 명문 클럽.",
    hints: ["청주 대표", "충북 경제인", "명문 클럽"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "cc002",
    name: "제천CC",
    region: "충청",
    province: "충북",
    lat: 37.1434,
    lng: 128.1914,
    holes: 18,
    established: 1986,
    description: "제천의 명품 골프장. 월악산 근처로 산악미가 뛰어남.",
    hints: ["제천 위치", "월악산 근처", "산악 경관"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "cc003",
    name: "음성CC",
    region: "충청",
    province: "충북",
    lat: 36.6968,
    lng: 127.3009,
    holes: 18,
    established: 1990,
    description: "음성의 고급 골프장. 축산업 발달로 유명한 지역 위치.",
    hints: ["음성 축산지", "고급 시설", "충북 중부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "cc004",
    name: "대전CC",
    region: "충청",
    province: "충남",
    lat: 36.3504,
    lng: 127.3845,
    holes: 18,
    established: 1987,
    description: "대전의 중심 골프장. 과학도시 대전의 대표 명문 클럽.",
    hints: ["대전 중심", "과학도시", "충남 대표"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "cc005",
    name: "천안CC",
    region: "충청",
    province: "충남",
    lat: 36.7940,
    lng: 127.1360,
    holes: 18,
    established: 1991,
    description: "천안의 프리미엄 골프장. 독립기념관으로 유명한 역사의 도시.",
    hints: ["천안 위치", "독립기념관", "역사의 도시"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "cc006",
    name: "공주CC",
    region: "충청",
    province: "충남",
    lat: 36.4565,
    lng: 127.1190,
    holes: 18,
    established: 1985,
    description: "공주 백제 유적지 근처의 골프장. 역사와 자연이 어우러진 코스.",
    hints: ["공주 백제", "유적지 근처", "역사 유산"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "cc007",
    name: "보령CC",
    region: "충청",
    province: "충남",
    lat: 36.2788,
    lng: 126.5727,
    holes: 18,
    established: 1992,
    description: "서해 해안 근처의 골프장. 보령머드축제로 유명한 지역.",
    hints: ["보령 해안", "머드축제", "서해 인근"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  // 경상
  {
    id: "ks001",
    name: "대구CC",
    region: "경상",
    province: "대구",
    lat: 35.8991,
    lng: 128.6054,
    holes: 18,
    established: 1985,
    description: "대구의 최고급 골프장. 대구 재계의 명문 클럽으로 이름이 높음.",
    hints: ["대구 최고급", "재계 명문", "영남 대표"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks002",
    name: "경주CC",
    region: "경상",
    province: "경북",
    lat: 35.8270,
    lng: 129.2200,
    holes: 18,
    established: 1989,
    description: "불국사, 석굴암이 있는 경주의 문화유산 도시에 위치한 골프장.",
    hints: ["경주 불국사", "문화유산", "신라 고도"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks003",
    name: "포항CC",
    region: "경상",
    province: "경북",
    lat: 36.0195,
    lng: 129.3687,
    holes: 18,
    established: 1987,
    description: "포항의 명품 골프장. 제철산업으로 유명한 포항의 대표 레저시설.",
    hints: ["포항 제철", "산업도시", "동해 해안"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks004",
    name: "김천CC",
    region: "경상",
    province: "경북",
    lat: 36.1273,
    lng: 128.7179,
    holes: 18,
    established: 1990,
    description: "김천의 고급 골프장. 직지심체요절로 유명한 역사도시.",
    hints: ["김천 직지", "인쇄 유산", "경북 중부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks005",
    name: "부산CC",
    region: "경상",
    province: "부산",
    lat: 35.1796,
    lng: 129.0685,
    holes: 18,
    established: 1984,
    description: "부산의 대표 골프장. 해양 도시 부산의 해운 업계 선호 클럽.",
    hints: ["부산 해운", "항구 도시", "해양 산업"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks006",
    name: "울산CC",
    region: "경상",
    province: "울산",
    lat: 35.5394,
    lng: 129.3140,
    holes: 18,
    established: 1988,
    description: "울산의 프리미엄 골프장. 자동차 및 조선 산업의 중심지.",
    hints: ["울산 자동차", "조선 산업", "산업도시"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks007",
    name: "창원CC",
    region: "경상",
    province: "경남",
    lat: 35.2271,
    lng: 128.5793,
    holes: 18,
    established: 1986,
    description: "창원의 명문 골프장. 기계산업의 중심도시에 위치.",
    hints: ["창원 기계", "산업 중심", "경남 동부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks008",
    name: "진주CC",
    region: "경상",
    province: "경남",
    lat: 35.1808,
    lng: 128.0755,
    holes: 18,
    established: 1991,
    description: "진주의 고급 골프장. 진주성으로 유명한 역사도시.",
    hints: ["진주성 역사", "남강 주변", "경남 서부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "ks009",
    name: "통영CC",
    region: "경상",
    province: "경남",
    lat: 34.8253,
    lng: 128.4365,
    holes: 18,
    established: 1993,
    description: "통영의 해안 골프장. 해상 관광과 미항으로 유명한 도시.",
    hints: ["통영 해안", "미항 도시", "해상 관광"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  // 전라
  {
    id: "jl001",
    name: "광주CC",
    region: "전라",
    province: "광주",
    lat: 35.1595,
    lng: 126.8526,
    holes: 18,
    established: 1987,
    description: "광주의 대표 골프장. 5.18 민주화운동 유적지가 있는 도시.",
    hints: ["광주 민주화", "전남 중심", "호남 대표"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jl002",
    name: "전주CC",
    region: "전라",
    province: "전북",
    lat: 35.8242,
    lng: 127.1470,
    holes: 18,
    established: 1985,
    description: "전주의 명문 골프장. 한옥마을로 유명한 전통 도시.",
    hints: ["전주 한옥", "전통 문화", "호남 북부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jl003",
    name: "익산CC",
    region: "전라",
    province: "전북",
    lat: 35.9425,
    lng: 126.9556,
    holes: 18,
    established: 1988,
    description: "익산의 고급 골프장. 미륵사지로 유명한 문화유산 도시.",
    hints: ["익산 미륵사", "백제 유산", "전북 중부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jl004",
    name: "전주힐스CC",
    region: "전라",
    province: "전북",
    lat: 35.8628,
    lng: 127.2190,
    holes: 18,
    established: 1996,
    description: "전주 근처의 고급 리조트형 골프장. 자연경관이 뛰어남.",
    hints: ["전주 힐스", "리조트형", "자연경관"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jl005",
    name: "목포CC",
    region: "전라",
    province: "전남",
    lat: 34.8118,
    lng: 126.3919,
    holes: 18,
    established: 1989,
    description: "목포의 해안 골프장. 다도해 해상국립공원 근처.",
    hints: ["목포 해안", "다도해", "해양 관광"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jl006",
    name: "순천CC",
    region: "전라",
    province: "전남",
    lat: 34.9501,
    lng: 127.4889,
    holes: 18,
    established: 1992,
    description: "순천의 명품 골프장. 순천만 습지 보전지역 근처.",
    hints: ["순천만 습지", "생태 도시", "전남 동부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jl007",
    name: "여수CC",
    region: "전라",
    province: "전남",
    lat: 34.7400,
    lng: 127.7369,
    holes: 18,
    established: 1994,
    description: "여수의 프리미엄 골프장. 여수해상케이블카로 유명한 관광지.",
    hints: ["여수 해상", "해상케이블카", "해양 관광"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jl008",
    name: "나주CC",
    region: "전라",
    province: "전남",
    lat: 35.0190,
    lng: 126.7405,
    holes: 18,
    established: 1991,
    description: "나주의 고급 골프장. 영산강 주변의 아름다운 자연.",
    hints: ["나주 영산강", "서남부", "전남 중심"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  // 제주
  {
    id: "jj001",
    name: "제주CC",
    region: "제주",
    province: "제주",
    lat: 33.4996,
    lng: 126.5312,
    holes: 18,
    established: 1993,
    description: "제주의 명품 골프장. 한라산 경관을 배경으로 한 최고급 리조트.",
    hints: ["제주 한라산", "리조트 골프", "관광지"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jj002",
    name: "서귀포CC",
    region: "제주",
    province: "제주",
    lat: 33.2565,
    lng: 126.5690,
    holes: 18,
    established: 1995,
    description: "서귀포의 해안 골프장. 성산일출봉 근처의 경치 좋은 위치.",
    hints: ["서귀포 일출봉", "해안 경관", "관광 명소"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jj003",
    name: "제주레이크스CC",
    region: "제주",
    province: "제주",
    lat: 33.4526,
    lng: 126.6789,
    holes: 18,
    established: 1997,
    description: "제주의 프리미엄 lakeside 골프장. 아름다운 호수 경관.",
    hints: ["제주 호수", "레이크사이드", "프리미엄"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jj004",
    name: "애월CC",
    region: "제주",
    province: "제주",
    lat: 33.5145,
    lng: 126.3459,
    holes: 18,
    established: 1996,
    description: "애월의 해안 골프장. 제주 서쪽 아름다운 해변 인근.",
    hints: ["애월 해안", "해변 경관", "제주 서부"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
  {
    id: "jj005",
    name: "하귀CC",
    region: "제주",
    province: "제주",
    lat: 33.5234,
    lng: 126.4015,
    holes: 18,
    established: 1998,
    description: "하귀의 고급 골프장. 제주의 최북단 지역, 관광 코스.",
    hints: ["하귀 해안", "제주 북부", "해안 경관"],
    features: ["좋은 시설", "친절한 서비스"],
    recommendedClubs: ["드라이버", "아이언"],
    difficulty: "중간",
    difficultyTips: ["정확한 샷이 필요합니다", "클럽 선택을 신중하게 하세요"]
  },
];

export const regionList = [
  "서울/경기",
  "강원",
  "충청",
  "경상",
  "전라",
  "제주",
] as const;

export function getCoursesByRegion(region: string): GolfCourse[] {
  return golfCourses.filter((course) => course.region === region);
}

export function getRandomCourse(): GolfCourse {
  return golfCourses[Math.floor(Math.random() * golfCourses.length)];
}

export function getRandomCourseFromRegion(region: string): GolfCourse | undefined {
  const courses = getCoursesByRegion(region);
  return courses.length > 0
    ? courses[Math.floor(Math.random() * courses.length)]
    : undefined;
}
